"""
generate training batches tensor for DINModel, which is used in DINTrainer. DONE
"""

from __future__ import print_function

from typing import Any, Tuple

import torch
from torch import Generator
from torch.utils.data import DataLoader, TensorDataset
import numpy as np


def iterate_minibatches(*tensors: Tuple[Any, Any], batch_size: int=4096, shuffle: bool=True, cycle: bool=True, **kw):
    """generate training batches for DINModel, which is used in DINTrainer
    
    :param: tensors: the input data, which is used to generate training batches for DINModel, and the shape of tensors is (batch_size, seq_len)
    :param: batch_size: the batch size of training batches, which is used to generate training batches for DINModel, and the default value is 4096
    :param: shuffle: whether to shuffle the input data, which is used to generate training batches for DINModel, and the default value is True
    :param: cycle: whether to cycle the input data, which is used to generate training batches for DINModel, and the default value is True
    :param: **kw: other parameters, which is used to generate training batches for DINModel, and the default value is empty
    :return: batch_x, batch_y. 
        batch_x is the matrix of user behaviors, which is used as input of DINModel, and the shape of batch_x is (batch_size, seq_len). 
        batch_y is the matrix of positive labels, which is used as input of DINModel, and the shape of batch_y is (batch_size, 1)
    """
    dataLoader = DataLoader(TensorDataset(*tensors), batch_size=batch_size, shuffle=shuffle)
    while True:
        yield from dataLoader
        print('cycle')
        if not cycle:
            break


class Train_instance:
    """读取训练数据文件, 并返回历史矩阵和正标签"""
    def __init__(self, parall: int=4):
        self.parall = parall


    def read_one_instrance_file(self, traing_instaces_path: str, sec_count_id: str, item_num: int) -> Tuple[torch.Tensor, torch.Tensor]:
        """read one training data file, which is generated by generate_train_and_test_data.py, and return the history matrix and positive labels

        :param: traing_instaces_path: the path of training data files, which are generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + sec_count_id
        :param: sec_count_id: the id of training data file, which is generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + sec_count_id
        :param: item_num: the number of items, which is used to fill the absence of items in the training data, and the absence is represented by item_num
        :return: 
            history_matrix.  (N, seq_len)
            positive_labels. (N, 1)
        """
        file_path = traing_instaces_path + '_{}'.format(sec_count_id)
        historys, labels = [], []
        with open(file_path) as f:
            for line in f:
                user, history, label = line.split('|')
                historys.append([int(st) for st in history.split(',')])
                labels.append(int(label))
        features = torch.LongTensor(historys)
        features[features < 0] = item_num
        labels = torch.LongTensor(labels)
        return features, labels
    
    '''
    def read_files(self, traing_instaces_path, sec_count_ids, pipe):
        """read some training data files, which are generated by generate_train_and_test_data.py, and concatenate them into one matrix, which is used to generate training batches for DINModel
        
        :param: traing_instaces_path: the path of training data files, which are generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + sec_count_id
        :param: sec_count_ids: the ids of training data files, which are generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + sec_count_id
        :param: pipe: the pipe used to communicate with the parent process, which is used   to send the concatenated history matrix and positive labels to the parent process   
        :return: None. the concatenated history matrix and positive labels are sent to the parent process through the pipe
        """
        hs, la = [], []
        for id in sec_count_ids:
            history, labels = self.read_one_instrance_file(traing_instaces_path, id)
            hs.append(history)
            la.append(labels)
        print('read traning data over at pid {}'.format(os.getpid()))
        pipe.send((torch.cat(hs, dim=0), torch.cat(la, dim=0)))

    def read_all_instances_files(self, traing_instaces_path, seg_couts):
        """read all the training data files, which are generated by generate_train_and_test_data.py, and concatenate them into one matrix, which is used to generate training batches for DINModel
        :param: traing_instaces_path: the path of training data files, which are generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + seg_count_id
        :param: seg_couts: the number of training data files, which are generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + seg_count_id
        :return: history_matrix, positive_labels. the concatenated history matrix and positive labels, which are used to generate training batches for DINModel, and the shape of history_matrix is (batch_size, seq_len), and the shape of positive_labels is (batch_size, 1)  
        """
        import multiprocessing as mp

        # 1. 初始化多进程
        process = []                                # 存放所有进程
        pipes = []                                  # 存放进程间通信管道
        job_size = int(seg_couts / self.parall)     # 每个进程处理多少文件
        file_couts = list(range(seg_couts))         # 所有文件编号 [0,1,2,...]
        if seg_couts % self.parall != 0:
            self.parall += 1                        # 如果不能整除，多开一个进程
        
        # 2. 创建进程 + 管道(进程间通信)
        """
        - a: 主进程的收信口
        - b: 子进程的发信口
        - p: 去干活的子进程
        
        1. 主进程 -> 创建管道 a ←→ b, 创建进程 p
        2. 把 b 交给 子进程p, p.start() 启动
        3. 子进程p拿着 b 去读文件, 读完 → b.send(his, labels)
        4. 主进程拿着 a → a.recv() 收数据
        """
        for i in range(self.parall):
            a, b = mp.Pipe()                        # 创建管道，用于进程间传数据
            pipes.append(a)
            p = mp.Process(
                target = self.read_files,           # 子进程执行的函数
                args = (traing_instaces_path, file_couts[i * job_size : (i + 1) * job_size], b)
            )
            process.append(p)
            p.start()                               # 启动进程
        
        # 3. 主进程接收所有子进程的数据
        history, lables = [], []
        for pipe in pipes:
            (his, las) = pipe.recv()                # 接收子进程传回的数据
            history.append(his)
            lables.append(las)

        # 4. 等待所有进程结束
        for p in process:
            p.join()
        
        # 5. 拼接所有数据并返回
        his = torch.cat(history, dim=0)             # 拼接所有历史行为序列
        lables = torch.cat(lables, dim=0)           # 拼接所有标签
        assert len(his) == len(lables)              # 保证样本数一致
        return his, lables
    '''

    def read_train_instances_files(self, traing_instaces_path: str, seg_couts: int, item_num: int) -> Tuple[torch.Tensor, torch.Tensor]:
        """read all the training data files, which are generated by generate_train_and_test_data.py, and concatenate them into one matrix
        
        :param: traing_instaces_path: the path of training data files, which are generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + seg_count_id
        :param: seg_couts: the number of training data files, which is generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + seg_count_id
        :param: item_num: the number of items, which is used to fill the absence of items in the training data, and the absence is represented by item_num  
        :return: 
            history_matrix.  (N, seq_len)
            positive_labels. (N, 1)
        """
        his_maxtix = None
        labels = None
        for i in range(seg_couts):
            part_his, part_labels = self.read_one_instrance_file(traing_instaces_path, i, item_num)
            if his_maxtix is not None:
                his_maxtix = torch.cat((his_maxtix, part_his), 0)
                labels = torch.cat((labels, part_labels), 0)
            else:
                his_maxtix = part_his
                labels = part_labels
    
        # len()等价tensor.shape[0]
        assert len(his_maxtix) == len(labels)
        return his_maxtix, labels


    def read_validation_instances_file(self, validation_instance_path: str, item_num: int) -> torch.Tensor:
        """read the validation data file, which is generated by generate_train_and_test_data.py, and return the history matrix and labels
        
        :param: validation_instance_path: the path of validation data file, which is generated by generate_train_and_test_data.py, and the file name is validation_instance_path
        :param: item_num: the number of items, which is used to fill the absence of items in the validation data, and the absence is represented by item_num
        :return: validation_data. the matrix of user behaviors, which is used as input of DINModel, and the absence of items is filled with item_num. 
                 the shape of validation_data is (N, seq_len) 
        """
        historys, labels = [], []
        with open(validation_instance_path) as f:
            line = f.readline()
            while line:
                user, history, label=line.split('|')
                historys.append([int(st) for st in history.split(',')])
                labels.append([int(st) for st in label.split(',')])
                line = f.readline()

        # validation_labels: the matrix of positive labels, which is used as input of DINModel, and the shape of validation_labels is (batch_size, 1)
        # List[List[int]]
        self.validation_labels = labels
        
        # (N, seq_len)
        validation_data = torch.LongTensor(historys)
        validation_data[validation_data < 0] = item_num
        return validation_data


    def read_test_instances_file(self, test_instance_path: str, item_num: int) -> torch.Tensor:
        """read the test data file, which is generated by generate_train_and_test_data.py, and return the history matrix and labels
        
        :param: test_instance_path: the path of test data file, which is generated by generate_train_and_test_data.py, and the file name is test_instance_path
        :param: item_num: the number of items, which is used to fill the absence of items in the test data, and the absence is represented by item_num
        :return: test_data. the matrix of user behaviors, which is used as input of DINModel, and the absence of items is filled with item_num. 
                 the shape of test_data is (N, seq_len)
        """
        historys, labels = [], []
        with open(test_instance_path) as f:
            line = f.readline()
            while line:
                user, history, label = line.split('|')
                historys.append([int(st) for st in history.split(',')])
                labels.append([int(st) for st in label.split(',')])
                line = f.readline()
        # List[List[int]]
        self.test_labels = labels
        
        # (N, seq_len)
        test_data = torch.LongTensor(historys)
        test_data[test_data < 0] = item_num
        return test_data
    

    def training_batches(self, traing_instaces_path: str, seg_couts: int, item_num: int, batchsize: int=300):
        """generate training batches for DINModel, which is used in DINTrainer
        
        :param: traing_instaces_path: the path of training data files, which is generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + seg_count_id
        :param: seg_couts: the number of training data files, which is generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + seg_count_id
        :param: item_num: the number of items, which is used to fill the absence of items in the training data, and the absence is represented by item_num
        :param: batchsize: the batch size of training batches, which is used to generate training batches for DINModel, and the default value is 300
        :return: train_loader. the DataLoader object, which is used to generate training batches for DINModel, 
                 and the shape of each batch is (batch_size, seq_len) for history_matrix and (batch_size, 1) for positive_labels
        """
        # read all the training data files, and concatenate them into one matrix, which is used to generate training batches for DINModel
        history_matrix, positive_labels = self.read_train_instances_files(traing_instaces_path, seg_couts, item_num)
        train_loader = DataLoader(
            dataset=TensorDataset(history_matrix, positive_labels), 
            batch_size=batchsize, 
            shuffle=True, 
            num_workers=4
        )
        
        while True:
            yield from train_loader


    def get_training_data(self, traing_instaces_path: str, seg_couts: int, item_num: int) -> Tuple[torch.Tensor, torch.Tensor]:
        """generate training data for DINModel, which is used in DINTrainer
        
        :param: traing_instaces_path: the path of training data files, which are generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + seg_count_id
        :param: seg_couts: the number of training data files, which is generated by generate_train_and_test_data.py, and the file name is traing_instaces_path + '_' + seg_count_id
        :param: item_num: the number of items, which is used to fill the absence of items in the training data, and the absence is represented by item_num
        :return: history_matrix, positive_labels. 
            history_matrix is the matrix of user behaviors, which is used as input of DINModel, and the absence of items is filled with item_num. (N, seq_len)
            positive_labels is the matrix of positive labels, which is used as input of DINModel, and the shape of positive_labels is (N, 1)
        """
        # read all the training data files, and concatenate them into one matrix, which is used to generate training batches for DINModel
        history_matrix, positive_labels = self.read_train_instances_files(traing_instaces_path, seg_couts, item_num)
        
        # 打乱训练数据的顺序, 避免模型过拟合
        index = np.arange(len(history_matrix))
        np.random.shuffle(index)
        assert len(history_matrix) == len(positive_labels)

        history_matrix = history_matrix[index]
        positive_labels = positive_labels[index]
        return history_matrix, positive_labels


    def generate_training_records(self, training_instances: torch.Tensor, training_labels: torch.Tensor, batch_size: int=1024):
        """generate training records for DINModel, which is used in DINTrainer 
        
        :param: training_instances: the training instances, which are used as input of DINModel, and the shape of training_instances is (batch_size, seq_len)
        :param: training_labels: the positive labels, which are used as input of DINModel, and the shape of training_labels is (batch_size, 1)
        :param: batch_size: the batch size, which is used to generate training records for DINModel, and the default value is 1024
        :return: batch_x, batch_y. 
                batch_x is the matrix of user behaviors, which is used as input of DINModel, and the shape of batch_x is (batch_size, seq_len). 
                batch_y is the matrix of positive labels, which is used as input of DINModel, and the shape of batch_y is (batch_size, 1)    
        """
        for batch_x, batch_y in iterate_minibatches(training_instances, training_labels, batch_size=batch_size):
            yield batch_x, batch_y


    def validation_batches(self, validation_instances_path: str, item_num: int, batchsize: int=100) -> DataLoader:
        """generate validation batches for DINModel, which is used in DINTrainer
    
        :param: validation_instances_path: the path of validation data files, which are generated by generate_train_and_test_data.py, and the file name is validation_instances_path + '_' + seg_count_id
        :param: item_num: the number of items, which is used to fill the absence of items in the validation data, and the absence is represented by item_num
        :param: batchsize: the batch size, which is used to generate validation batches for DINModel, and the default value is 100
        :return: batch_x, batch_y. 
            batch_x is the matrix of user behaviors, which is used as input of DINModel, and the shape of batch_x is (batch_size, seq_len). 
            batch_y is the matrix of positive labels, which is used as input of DINModel, and the shape of batch_y is (batch_size, 1)
        """
        # (N, seq_len)
        test_instances_matrix = self.read_validation_instances_file(validation_instances_path, item_num)

        # mindex: 每个验证样本在原始验证集中的位置编号
        # 作用: 在样本被打乱后依然能找到它原来的位置, 保证评估指标正确计算
        mindex = torch.tensor(np.arange(len(test_instances_matrix)))
        test_loader = DataLoader(
            dataset=TensorDataset(test_instances_matrix, mindex),
            batch_size=batchsize,
            shuffle=True,
            num_workers=4
        )
        while True:
            yield from test_loader


    def test_batches(self, test_instances_path: str, item_num: int, batchsize: int=100):

        """generate test batches for DINModel, which is used in DINTrainer
        :param: test_instances_path: the path of test data files, which are generated by generate_train_and_test_data.py, and the file name is test_instances_path + '_' + seg_count_id
        :param: item_num: the number of items, which is used to fill the absence of items in the test data, and the absence is represented by item_num
        :param: batchsize: the batch size, which is used to generate test batches for DINModel, and the default value is 100
        :return: batch_x, batch_y. 
            batch_x is the matrix of user behaviors, which is used as input of DINModel, and the shape of batch_x is (batch_size, seq_len). 
            batch_y is the matrix of positive labels, which is used as input of DINModel, and the shape of batch_y is (batch_size, 1)
        """
        test_instances_matrix = self.read_test_instances_file(test_instances_path, item_num)

        # mindex: 每个测试样本在原始测试集中的位置编号
        # 作用: 在样本被打乱后依然能找到它原来的位置, 保证评估指标正确计算
        mindex = torch.tensor(np.arange(len(test_instances_matrix)))
        test_loader: DataLoader = DataLoader(
            dataset=TensorDataset(test_instances_matrix, mindex),
            batch_size=batchsize,
            shuffle=True,
            num_workers=4
        )
        while True:
            yield from test_loader
    


if __name__=="__main__":
    train_instances: Train_instance = Train_instance()
    batch_generator: Generator = train_instances.training_batches('./data/mock/train_instances',10)
    test_generator: Generator = train_instances.test_batches('./data/mock/test_instances', batchsize=5)
    hh, ss = test_generator.__next__()
    print(hh)
    print(ss)
    # for h in enuhh):
    #    print(hh[i:i+1,:])
